# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pr: 
  - master

pool: 
  name: '10.5'
  vmImage: 'windows-latest'
  
variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: "DemoApp"
  
steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 8.x
      performMultiLevelLookup: true
      
  - task: DotNetCoreCLI@2
    displayName: Restore NuGet packages
    inputs:
      command: 'restore'
      projects: '**/$(projectName).csproj'
      
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/$(projectName).csproj'
      arguments: '--configuration $(buildConfiguration)'
      
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/$(projectName).csproj'
      arguments: '--configuration $(buildConfiguration) /p:PublishProfile=Properties/PublishProfiles/DevOpsProfile.pubxml --output $(Build.ArtifactStagingDirectory)/$(projectName)'
      zipAfterPublish: True
  
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(projectName)'
      publishLocation: 'pipeline'
      artifact: '$(projectName)'
